version: "3.8"

services:
  postgres:
    image: postgres #hub.docker.com
    ports:
      - "5232:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: review
      POSTGRES_PASSWORD: password

  redis:
    image: redis #hub.docker.com
    ports:
        - "6379:6379"
